global: 
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "ec2-agent"
    scrape_interval: 15s
    static_configs:
      - targets: ["34.239.116.31:9100"]
  - job_name: "github-agent"
    scrape_interval: 15s
    static_configs:
      - targets: ["52.201.216.196:9100"]
  - job_name: "load-balancer-agent"
    scrape_interval: 15s
    static_configs:
      - targets: ["3.83.167.214:9100"]
  - job_name: "dynamodb-agent"
    scrape_interval: 15s
    static_configs:
      - targets: ["3.83.133.220:9100"]
  - job_name: "cloud-watch-agent"
    scrape_interval: 15s
    static_configs:
      - targets: ["54.175.173.65:9100"]
  - job_name: "iam-agent"
    scrape_interval: 15s
    static_configs:
      - targets: ["52.201.215.145:9100"]
  - job_name: "s3-agent"
    scrape_interval: 15s
    static_configs:
      - targets: ["44.212.14.29:9100"]

  
  
  
