global: 
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "ec2-agent"
    scrape_interval: 15s
    static_configs:
      - targets: ["54.91.207.224:9100"]
  - job_name: "github-agent"
    scrape_interval: 15s
    static_configs:
      - targets: ["3.93.231.214:9100"]
  - job_name: "load-balancer-agent"
    scrape_interval: 15s
    static_configs:
      - targets: ["3.84.195.49:9100"]
  - job_name: "dynamodb-agent"
    scrape_interval: 15s
    static_configs:
      - targets: ["34.204.8.253:9100"]
  - job_name: "cloud-watch-agent"
    scrape_interval: 15s
    static_configs:
      - targets: ["3.92.182.149:9100"]
  - job_name: "iam-agent"
    scrape_interval: 15s
    static_configs:
      - targets: ["44.202.91.201:9100"]
  - job_name: "s3-agent"
    scrape_interval: 15s
    static_configs:
      - targets: ["44.211.166.92:9100"]

  
  
  
